main_app/urls.py
from django.urls import path
from . import views
from .views import venue_list 
from .views import add_event_photo
from .views import event_detail



urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    
    path('events/<int:event_id>/', views.event_detail_model, name='detail'),
    path('events/', views.EventList.as_view(), name='index'),
    path('events/hub/', views.event_hub, name="hub"),
    path('events/mine/', views.MyEventList.as_view(), name='myindex'),
    path('events/mine/include_past', views.MyWithPastEventList.as_view(), name='myindex_withpast'),
    path('events/myowned/', views.MyOwnedEventList.as_view(), name='myownedindex'),
    path('events/myowned/include_past', views.MyOwnedWithPastEventList.as_view(), name='myownedindex_withpast'),
    path('events/search', views.event_search, name='search'),
    path('events/searchresults', views.SearchResultsList.as_view(), name='search_results'),
    # path('events/mine', views.MyEventList.as_view(), name='myindex'), 
    path('events/create/', views.EventCreate.as_view(), name='events_create'),

    # URL patterns for venues
    path('venues/', venue_list, name='venue_list'),  
    path('venues/<int:pk>/', views.venue_detail, name='venue_detail'),
    path('venues/create/', views.venue_create, name='venue_create'),
    path('venues/<int:pk>/update/', views.venue_update, name='venue_update'),
    path('venues/<int:pk>/delete/', views.venue_delete, name='venue_delete'),

    path('accounts/signup/', views.signup, name='signup'),

    path('event/<int:pk>/edit/', views.EventEdit.as_view(), name='event_edit'),
    path('event/<int:pk>/delete/', views.EventDelete.as_view(), name='event_delete'),
    path('events/<int:event_id>/assoc_reservation/', views.assoc_reservation, name="assoc_reservation"),
    path('events/assoc_reservation/', views.assoc_external_reservation, name="assoc_external_reservation"),
    path('events/<int:event_id>/unassoc_reservation/<int:reservation_id>', views.unassoc_reservation, name="unassoc_reservation"),

    path('event/<int:event_id>/edit_reservation/<int:reservation_id>', views.edit_reservation, name='event_edit_reservation'),

    path('events/<int:event_id>/add_photo/', views.add_event_photo, name='add_event_photo'),
    path('events/catagories/<event_id>/', event_detail, name='event_detail'),

    path('profile/create/', views.ProfileCreate.as_view(), name='profile_create'),
    path('profile/<int:pk>/update/', views.ProfileUpdate.as_view(), name='profile_update'),
]

whats_happening/urls.py
from django.contrib import admin
from django.urls import path, include 


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
  # include the built-in auth urls for the built-in views
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import date
from django.utils import timezone
from django.urls import reverse

from django.db.models.signals import post_save
from django.dispatch import receiver



# Create your models here.
    
class Venue(models.Model):
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    # image = models.ImageField(upload_to='images/', blank=True)
    
    def __str__(self):
        return self.name


class Reservation(models.Model):
    attendee = models.ForeignKey(User, on_delete=models.CASCADE)
    guests = models.IntegerField(default=0)
    
    def __str__(self):
        return f"{self.attendee} - guests: {self.guests}"
    

class Event(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    venue = models.ForeignKey(Venue, on_delete=models.CASCADE, null=True, blank=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    time = models.TimeField()
    end_time = models.TimeField(null=True, blank=True)

    # recurring = models.BooleanField(default=False)
    reservations = models.ManyToManyField(Reservation)
    # recurrences = models.ForeignKey('Recurrences', on_delete=models.CASCADE, null=True, blank=True)
    # image = models.ImageField(upload_to='images/', blank=True)

    
    def __str__(self):
        return self.name
    
    class Meta:
        ordering = ['date']
    
class Photo(models.Model):
    image_url = models.URLField()
    description = models.TextField()
    event = models.ForeignKey(Event, on_delete=models.CASCADE)

    def __str__(self):
        return f"Photo for event: {self.event.name} @{self.image_url}"
    

# User Profile Model
# This will store a default keyword, city or zip code to search by
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    keyword = models.CharField(max_length=100)
    
    def __str__(self):
        return f"Profile for { self.user }"
    
    # this is the get_absolute_url method
    # it redirects to the detail page where appropriate
    def get_absolute_url(self):
        return reverse('hub', kwargs={})
    

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

main_app/forms.py
from django import forms
from django.forms import ModelForm
from .models import Event, Venue, Photo, Profile


class EventForm(ModelForm):
    time = forms.TimeField(
        # input_formats=['%I:%M %p'],
        # widget=forms.TimeInput(format='%H:%M:%p')
    )

    class Meta:
        model = Event
        fields = ['name', 'venue', 'description', 'date', 'time', 'end_time']
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
        }

    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        self.fields['venue'].queryset = Venue.objects.all()

class VenueForm(ModelForm):
    class Meta:
        model = Venue
        fields = ['name', 'location', 'description']


class SearchForm(forms.Form):
    keyword = forms.CharField(label='Search', max_length=100)

class PhotoForm(forms.ModelForm):
    class Meta:
        model = Photo
        fields = ['image_url', 'description']
        
        

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['keyword']

main_app/views.py
import datetime
import uuid
import boto3
import os

from botocore.exceptions import NoCredentialsError
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.db.models import Q
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.utils.dateparse import parse_date, parse_time

from .models import Event, Venue, Reservation, Profile
from .forms import EventForm, VenueForm
from .models import Photo

from .ticketmaster_api import get_ticketmaster_events
from .ticketmaster_api import get_event_details

# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def event_search(request):
    return render(request, 'events/search.html')

def events_index(request):
    events = Event.objects.all()
    return render(request, 'events/index.html', {'events': events})

# API call event search by keyword
def parse_api_event_data(events_data):
    events = []
    if events_data:
        for event in events_data.get('_embedded', {}).get('events', []):
            embedded = event.get('_embedded', {})
            venues = embedded.get('venues') if embedded else []
            venue_name = venues[0].get('name') if venues else None
            date_str = event.get('dates', {}).get('start', {}).get('localDate')
            time_str = event.get('dates', {}).get('start', {}).get('localTime')
            event_info = {
                'id': event.get('id'),
                'name': event.get('name'),
                'description': event.get('description'),
                'date': parse_date(date_str) if date_str else None,
                'time': parse_time(time_str) if time_str else None,
                'image_url': event.get('images', [])[0].get('url') if event.get('images') else None,
                'venue': venue_name
            }
            events.append(event_info)

    return events

def get_api_results_for_keyword(keyword):
    events_data = get_ticketmaster_events(keyword)
    return parse_api_event_data(events_data)

def get_api_results_for_keyword_and_date(keyword, date):
    events_data = get_ticketmaster_events(keyword, date)
    return parse_api_event_data(events_data)

# Api call event by id
def event_detail(request, event_id):
    event_data = get_event_details(event_id)  
#####
    # print(event_data)
#####
    if event_data:
        event_info = {
            'name': event_data.get('name'),
            'description': event_data.get('description'),
            'images': event_data.get('images', []),
            'venue': event_data.get('_embedded', {}).get('venues', [])[0].get('name') if event_data.get('_embedded', {}).get('venues') else None,
            'externalLinks': {
                'youtube': event_data.get('externalLinks', {}).get('youtube', [{}])[0].get('url') if event_data.get('externalLinks', {}).get('youtube') else None,
                'twitter': event_data.get('externalLinks', {}).get('twitter', [{}])[0].get('url') if event_data.get('externalLinks', {}).get('twitter') else None,
            },
            'info': event_data.get('info'),
            'location': {
                'address': event_data.get('_embedded', {}).get('venues', [])[0].get('address', {}).get('line1') if event_data.get('_embedded', {}).get('venues') else None,
                'city': event_data.get('_embedded', {}).get('venues', [])[0].get('city', {}).get('name') if event_data.get('_embedded', {}).get('venues') else None,
                'state': event_data.get('_embedded', {}).get('venues', [])[0].get('state', {}).get('name') if event_data.get('_embedded', {}).get('venues') else None,
                'country': event_data.get('_embedded', {}).get('venues', [])[0].get('country', {}).get('name') if event_data.get('_embedded', {}).get('venues') else None,
            },
            'start_date': event_data.get('dates', {}).get('start', {}).get('localDate'),
            'start_time': event_data.get('dates', {}).get('start', {}).get('localTime'),
        }
        print(event_info)
        return render(request, 'events/categories/event_detail.html', {'event': event_info})
    else:
        return HttpResponse("Event not found or an error occurred.")



## Event Index List Views
class EventList(ListView):
    model = Event
    template_name = 'events/index.html'
    
    def get_queryset(self):
        return Event.objects.filter(date__gte=datetime.date.today())

class MyEventList(EventList):
    def get_queryset(self):
        return Event.objects.filter(
            (Q(owner=self.request.user) | Q(reservations__attendee=self.request.user)) &
            Q(date__gte=datetime.date.today())
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'My Events'
        context['show_filter_options'] = True
        context['past_filter'] = 'hide'
        context['event_filter'] = 'all'
        return context
    
class MyWithPastEventList(MyEventList):
    def get_queryset(self):
        return Event.objects.filter(
            (Q(owner=self.request.user) | Q(reservations__attendee=self.request.user))
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['past_filter'] = 'show'
        return context
    
class MyOwnedEventList(MyEventList):
    def get_queryset(self):
        return Event.objects.filter(owner=self.request.user, date__gte=datetime.date.today())

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'My Owned Events'
        context['show_filter_options'] = True
        context['past_filter'] = 'hide'
        context['event_filter'] = 'owned'
        return context

class MyOwnedWithPastEventList(MyOwnedEventList):
    def get_queryset(self):
        return Event.objects.filter(owner=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['past_filter'] = 'show'
        return context

class SearchResultsList(EventList):
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Search Results'

        # Get external api search results and send onto template
        keyword = self.request.GET.get('keyword')
        date = self.request.GET.get('date')
        if date:
            context['external_event_list'] = get_api_results_for_keyword_and_date(keyword, date)
        else: 
            context['external_event_list'] = get_api_results_for_keyword(keyword)
        return context

    def get_queryset(self):
        q_objects = Q()

        # Keyword search checks event_name, venue_name, venue_description
        keyword = self.request.GET.get('keyword')
        if keyword:
            q_objects |= Q(name__icontains=keyword)
            q_objects |= Q(venue__name__icontains=keyword)
            q_objects |= Q(venue__location__icontains=keyword)

        # Search by date
        date = self.request.GET.get('date')
        if date:
            q_objects &= Q(date__gte=date)
        else:
            # If no date picked, filter out past events
            q_objects &= Q(date__gte=datetime.date.today())

        return Event.objects.filter(q_objects)


class DetailView(DetailView):
    model = Event
    template_name = 'events/detail.html'

def event_detail_model(request, event_id):
    event = Event.objects.get(id=event_id)
    try:
        reservation = event.reservations.get(attendee=request.user)
        print(event)
        return render(request, 'events/detail.html', {'event': event, 'reservation': reservation})
    except Reservation.DoesNotExist: 
        return render(request, 'events/detail.html', {'event': event})

@login_required
def assoc_reservation(request, event_id):
    # Create the reservation
    reservation = Reservation()
    reservation.attendee = request.user
    reservation.guests = request.POST["guests"]
    reservation.save()

    # Add it to the event
    Event.objects.get(id=event_id).reservations.add(reservation)

    # Redirect to event detail
    return redirect('detail', event_id=event_id)

@login_required
def assoc_external_reservation(request):
    # Create the reservation
    reservation = Reservation()
    reservation.attendee = request.user
    reservation.guests = request.POST["guests"]
    reservation.save()

    # Add it to the event
    event = Event()
    event.name = request.POST["name"]
    event.description = request.POST["description"]
    event.date = parse_date(request.POST["date"])
    event.time = parse_time(request.POST["time"])
    event.owner = User.objects.get(username='TheMachine')
    event.save()
    
    #get venue from api and save it to venue model
    try:
        venue = Venue.objects.get(name=request.POST["venue"])
    except:
        venue = Venue()
        venue.name = request.POST["venue"]
        venue.save()
        
    event.venue = venue

    # Save images
    photo = Photo(image_url=request.POST["photo_url"], event=event)
    photo.save()

    event.reservations.add(reservation)
    event.save()

    # Redirect to event detail
    return redirect('detail', event_id=event.id) 

@login_required
def unassoc_reservation(request, event_id, reservation_id):
    # Target the event
    Event.objects.get(id=event_id).reservations.remove(reservation_id)
    # Redirect to event detail
    return redirect('detail', event_id=event_id)

@login_required

main_app/templates/events/detail.html
{% extends 'base.html' %}
{% block content %}
<h1 class="center-align"> <strong>{{ event.name }}</strong> <br> <small>@</small><br> {{ event.venue }}</h1>
<!-- details page  -->
<div class="profile-card">
    {% with event.photo_set.all|first as photo %}
        {% if photo %}
            <img src="{{photo.image_url}}" alt="{{ event.name }}" class="profile-image">
        {% endif %}
    {% endwith %}
</div>

<div class="row">
    <div class="">
        <div class="card">
            <div class="card-content">
                <span class="card-title">{{ event.name }}</span>
                <p><strong>Date:</strong> {{ event.date }} at {{ event.time }}{% if event.end_time %} - {{ event.end_time }}{% endif %}</p>
                <p><strong>Venue:</strong> {{ event.venue }}</p>
            </div>
        </div>
    </div>
    <div class="">
        <div class = "card">
            <div class="card-content">
                <p><strong>Hosted by:</strong> {{ event.owner }}</p>
                <hr>
                <p>{{ event.description }}</p>
            </div>
        </div>
    </div>
</div>
<!-- Display photos -->
<div class="container-fluid">
    <div class="scroll-container">
        <div class="d-flex">
            {% for photo in event.photo_set.all %}
            <div class="image-card">
                <img src="{{photo.image_url}}" alt="{{ event.name }}">
            </div>
            {% endfor %}
        </div>
    </div>
</div>

<!-- Upload photo -->

<form action="{% url 'add_event_photo' event.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
    {% csrf_token %}
    <input type="file" name="photo-file">
    <br><br>
    <button type="submit" class="btn">Upload Photo</button>
</form>

{% if request.user == event.owner %}
    <div class = "options">
        <h2>User Options</h2>
        <a class="btn" href="{% url 'event_edit' event.id %}"><i class="fas fa-edit"></i>Edit</a>
        <br>
        <a class="btn" href="{% url 'event_delete' event.id %}"><i class="fas fa-trash-alt"></i>Delete</a>
    </div>
{% else %}
    <div class="card">
        <div class="card-title">
            <h2>Reservation</h2>
        </div>
        <div class="card-content">
            {% if reservation %}
                <div class="row">
                    <form action="{% url 'event_edit_reservation' event.id reservation.id %}" method="post" class="col s12">
                        {% csrf_token %}
                        <div class="row">
                            <div class="input-field col s4">
                                <a class="btn-floating btn waves-effect waves-light red white-text" href="javascript:decrement()" id="minus-button">-</a>
                            </div>
                            <div class="input-field col s4">
                                <label for="guests">Number of Guests:</label>
                                <input type="number" name="guests" min="0" max="10" value="{{ reservation.guests }}" id="guests">
                            </div>
                            <div class="input-field col s4">
                                <a class="btn-floating btn waves-effect waves-light white-text" href="javascript:increment()"" id="plus-button">+</a>
                            </div>
                        </div>
                        <button type="submit" class="btn"><i class="fas fa-calendar-plus"></i> Update Guest Count</button>
                    </form>
                    <br>&nbsp;<br>
                    <form action="{% url 'unassoc_reservation' event.id reservation.id %}" method="post" class="col s12">
                        {% csrf_token %}
                        <button type="submit" class="btn red"><i class="fas fa-calendar-minus"></i> I'm Not Going!</button>
                    </form>
                </div>
            {% else %}
                <div class="row">
                    <form action="{% url 'assoc_reservation' event.id %}" method="post">
                        {% csrf_token %}           
                        <div class="row">
                            <div class="input-field col s4">
                                <a class="btn-floating btn waves-effect waves-light red white-text disabled" href="javascript:decrement()" id="minus-button">-</a>
                            </div>
                            <div class="input-field col s4">
                                <label for="guests">Number of Guests:</label>
                                <input type="number" name="guests" min="0" max="10" value="0" id="guests">
                            </div>
                            <div class="input-field col s4">
                                <a class="btn-floating btn waves-effect waves-light white-text" href="javascript:increment()"" id="plus-button">+</a>
                            </div>
                        </div>
                        <button type="submit" class="btn"><i class="fas fa-calendar-plus"></i> I'm Going!</button>
                    </form>
                </div>
            {% endif %}
        </div>
    </div>
{% endif %}

<script>
    const minusBtnEl = document.getElementById("minus-button")
    const guestCountEl = document.getElementById("guests")
    const plusBtnEl = document.getElementById("plus-button")
    let guestNum = 0

    function increment() {
        guestCountEl.stepUp()
        minusBtnEl.classList.remove("disabled")
        if (guestCountEl.value >= 10) {
            plusBtnEl.classList.add("disabled")
        }
    }
    function decrement() {
        guestCountEl.stepDown()
        plusBtnEl.classList.remove("disabled")
        if (guestCountEl.value == 0) {
            minusBtnEl.classList.add("disabled")
        }
    }
</script>

{% endblock %}

main_app/templates/events/hub.html
{% extends 'base.html' %}
{% block content %}

    <br>
    <h1>My Event Hub</h1>
    <br>
    <ul class="collapsible popout" data-collapsible="popout">
        <li>

            <div class="collapsible-header">
                <div class="left-align"><i class="fas fa-chevron-right"></i>I'm planning...</div>
            </div>
            <div class="collapsible-body grey lighten-2">
                <div class="right-align black-text">
                    <a href="{% url 'events_create' %}"><i class="fas fa-plus black-text"> <span class="hub-link">Create Event</span></i></a>
                    <br>&nbsp;
                </div>
                {% for event in my_owned_events %}
                    <a href="{% url 'detail' event.id %}">
                        <div class="event-card">
                            <div class="card-body">
                                <h4 class="card-title">{{ event.name }}</h4>
                                <p class="card-text">
                                    Date: {{ event.date }} Time: {{ event.time }}
                                    {% if event.end_time %}
                                        - {{ event.end_time }}
                                    {% endif %}
                                </p>
                                {% if event.image_url %}
                                    <img class="card-img-top" src="{{ event.image_url }}" alt="{{ event.name }}">
                                {% endif %}
                                <!-- we can add more event details here -->
                                <p class="card-text">Venue: {{ event.venue }}</p>
                            </div>
                        </div>
                    </a>
                {% empty %}
                    <br>&nbsp;
                    <div class="card-panel red-text center-align">You have no upcoming events that you are planning yet</div>
                {% endfor %}

            </div>
        </li>
        <li>
            <div class="collapsible-header"><i class="fas fa-chevron-right"></i>I'm going to...</div>
            <div class="collapsible-body grey lighten-2">
                {% for event in my_rsvp_events %}
                    <a href="{% url 'detail' event.id %}">
                        <div class="event-card">
                            <div class="card-body">
                                <h4 class="card-title">{{ event.name }}</h4>
                                <p class="card-text">
                                    Date: {{ event.date }} Time: {{ event.time }}
                                    {% if event.end_time %}
                                        - {{ event.end_time }}
                                    {% endif %}
                                </p>
                                {% if event.image_url %}
                                    <img class="card-img-top" src="{{ event.image_url }}" alt="{{ event.name }}">
                                {% endif %}
                                <!-- we can add more event details here -->
                                <p class="card-text">Venue: {{ event.venue }}</p>
                                {% if event.owner == user %}
                                    <p class="grey-text smaller-text"><i class="fas fa-key"></i> I own this event!</p>
                                {% endif %}
                            </div>
                        </div>
                    </a>
                {% empty %}
                    <div class="card-panel red-text center-align">You have no upcoming events that you have reservations for</div>
                {% endfor %}
            </div>
        </li>
        <li class="active">
            <div class="collapsible-header">
                <i class="fas fa-chevron-right"></i>I could go...
            </div>
            <div class="collapsible-body grey lighten-2">

                <div class="right-align black-text">
                    {% if user.profile %}
                        <a href="{% url 'profile_update' user.profile.id %}" alt="Update Profile"><i class="fas fa-pen black-text"> <span class="hub-link">Update Profile</span></i></a>
                    {% else %}
                        <a href="{% url 'profile_create' %}"><i class="fas fa-pen black-text"> <span class="hub-link">Add Profile</span></i></a>
                    {% endif %}
                    <br>&nbsp;
                </div>
                {% for event in pref_events %}
                    <a href="{% url 'event_detail' event.id %}">
                        <div class="event-card">
                            <div class="card-body">
                                <h4 class="card-title">{{ event.name }}</h4>
                                <p class="card-text">
                                    Date: {{ event.date }} Time: {{ event.time }}
                                    {% if event.end_time %}
                                        - {{ event.end_time }}
                                    {% endif %}
                                </p>
                                {% if event.image_url %}
                                    <img class="card-img-top" src="{{ event.image_url }}" alt="{{ event.name }}">
                                {% endif %}
                                <!-- we can add more event details here -->
                                <p class="card-text">Venue: {{ event.venue }}</p>
                                {% if event.owner == user %}
                                    <p class="grey-text smaller-text"><i class="fas fa-key"></i> I own this event!</p>
                                {% endif %}
                            </div>
                        </div>
                    </a>
                {% empty %}
                    <div class="card-panel red-text center-align">No events found for your profile keyword</div>
                {% endfor %}
            </div>

        </li>    
    </ul>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const elems = document.querySelectorAll('.collapsible');
            const instances = M.Collapsible.init(elems, {});
        });
    </script>
{% endblock %}

main_app/templates/events/keyword.html
{% extends 'base.html' %}
{% block content %}

<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Search">
</form>


{% if events %}
    <h1>Events</h1>
    <div class="row">
        {% for event in events %}
            <div class="col-sm-4">
                <a href="{% url 'event_detail' event.id %}">
                <div class="event-card">
                    <div class="card-body">
                        <h3 class="card-title">{{ event.name }}</h3>
                        <p class="card-text">Date: {{ event.date }} Time: {{ event.time }}</p>
                        {% if event.image_url %}
                            <img class="card-img-top" src="{{ event.image_url }}" alt="{{ event.name }}">
                        {% endif %}
                        <!-- we can add more event details here -->
                        <p class="card-text">Venue: {{ event.venue }}</p>
                    </div>

                </div>
            </div>
        </a>
        {% endfor %}
    </div>
{% else %}
    <p>{{ error }}</p>
{% endif %}

{% endblock %}

main_app/templates/events/search.html
{% extends 'base.html' %}
{% block content %}

    <h1>Search Events</h1>
    <div class="search-container">

        <form action="{% url 'search_results' %}" method="get">
            <br>
            <label for="keyword">Keyword:</label>
            <input name="keyword" type="text">
            <label for="date">Start Date:</label>
            <input name="date" type="text" id="date">
            <br>&nbsp;<br>
            <button type="submit" class="btn">Search</button>
        </form>
        <br>
    </div>
    

    <script>
        // this is  js for the datepicker aka Calendar
        const dateEl = document.getElementById('date')
        // M is materialize's global variable
        M.Datepicker.init(dateEl, {
            format: 'yyyy-mm-dd',
            autoClose: true
        })
    </script>
{% endblock %}